name: davidgoldman
favicon: null
layout_spectrum: 0.22364054154604673
typography_spectrum: 0.89443
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#96a3b6'
    - '#6c83ac'
    - '#8e623f'
    - '#3a2514'
    - '#d5cbc1'
  brandStrength: 0.8125
  lightness: 0.8928532132413238
  saturation: 0.3113853947725147
  rhythmicContrast: 0.9284827075898647
purpose: []
